{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "k8s-logging-agent.fullname" . }}
  labels:
    {{- include "k8s-logging-agent.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "k8s-logging-agent.selectorLabels" . | nindent 6 }}
{{- end }}
